services:

  stockfinder_backend:
    build: ./flask_back
    image: stockfinder_backend:latest
    container_name: stockfinder_backend
    restart: always
    expose:
      - ${DOCKER_BACKEND_PORT}
    networks:
      back_front:
        ipv4_address: ${DOCKER_BACKEND_FRONTEND_IP}
      postgres:
        ipv4_address: ${DOCKER_BACKEND_POSTGRESQL_IP}
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 1024M
        reservations:
          cpus: '1'
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 600s
    env_file:
      - ./flask_back/.env
      - .env

  stockfinder_frontend:
    build: ./nextjs_front
    image: stockfinder_frontend:latest
    container_name: stockfinder_frontend
    restart: always
    expose:
      - ${DOCKER_FRONTEND_PORT}
    networks:
      - back_front
      - caddy_external_net
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 1024M
        reservations:
          cpus: '1'
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 600s
    labels:
      caddy: gpufinder.ovh
      caddy.route.reverse_proxy: "{{upstreams ${DOCKER_FRONTEND_PORT}}}"
    env_file:
      - ./nextjs_front/.env.production
      - .env

  postgres:
    image: postgres
    container_name: stockfinder_postgres
    restart: always
    shm_size: 128mb
    volumes:
     - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSGRESQL_USER}
      POSTGRES_PASSWORD: ${POSGRESQL_PASSWORD}
      POSTGRES_DB: ${POSGRESQL_DATABASE}
    expose:
      - ${POSGRESQL_PORT}
    networks:
      postgres:
        ipv4_address: ${POSGRESQL_IP}

  cloudflare_updater:
    build: ./cloudflare_updater
    image: cloudflare_updater
    container_name: cloudflare_updater
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 128M
        reservations:
          cpus: '1'
          memory: 64M
    env_file:
      - ./cloudflare_updater/.env



networks:
  back_front:
    name: back_front
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_BACKEND_FRONTEND_NETWORK}
          gateway: ${DOCKER_BACKEND_FRONTEND_GATEWAY}
  caddy_external_net:
    name: caddy_external_net
    external: true
  postgres:
    name: postgres
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_BACKEND_POSTGRESQL_NETWORK}
          gateway: ${DOCKER_BACKEND_POSTGRESQL_GATEWAY}
