services:

  stockfinder_backend:
    build: ./flask_back
    image: stockfinder_backend:latest
    container_name: stockfinder_backend
    restart: always
    ports:
      - ${DOCKER_BACKEND_PORT}:${DOCKER_BACKEND_PORT}
    networks:
      back_front:
        ipv4_address: ${DOCKER_BACKEND_FRONTEND_IP}
      postgres:
        ipv4_address: ${DOCKER_BACKEND_POSTGRESQL_IP}
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 1024M
        reservations:
          cpus: '1'
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 600s
    env_file:
      - ./flask_back/.env
      - .env

  stockfinder_frontend:
    build: ./nextjs_front
    image: stockfinder_frontend:latest
    container_name: stockfinder_frontend
    restart: always
    ports:
      - ${DOCKER_FRONTEND_PORT}:${DOCKER_FRONTEND_PORT}
    networks:
      - back_front
      - remoteproxy
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 1024M
        reservations:
          cpus: '1'
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 600s
    labels:
      traefik.enable: true
      traefik.http.routers.gpufinder_frontend.rule: Host(`gpufinder.ovh`) || Host(`www.gpufinder.ovh`)
      traefik.http.routers.gpufinder_frontend.entrypoints: http
      traefik.http.middlewares.gpufinder_frontend-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.gpufinder_frontend.middlewares: gpufinder_frontend-https-redirect
      traefik.http.routers.gpufinder_frontend-secure.entrypoints: https
      traefik.http.routers.gpufinder_frontend-secure.rule: Host(`gpufinder.ovh`) || Host(`www.gpufinder.ovh`)
      traefik.http.routers.gpufinder_frontend-secure.tls: true
      traefik.http.routers.gpufinder_frontend-secure.service: gpufinder_frontend
      traefik.http.services.gpufinder_frontend.loadbalancer.server.port: ${DOCKER_FRONTEND_PORT}
      traefik.docker.network: remoteproxy
    env_file:
      - ./nextjs_front/.env.production
      - .env

  postgres:
    image: postgres
    container_name: stockfinder_postgres
    restart: always
    shm_size: 128mb
    volumes:
     - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSGRESQL_USER}
      POSTGRES_PASSWORD: ${POSGRESQL_PASSWORD}
      POSTGRES_DB: ${POSGRESQL_DATABASE}
    ports:
      - ${POSGRESQL_PORT}:${POSGRESQL_PORT}
    networks:
      postgres:
        ipv4_address: ${POSGRESQL_IP}

networks:
  back_front:
    name: back_front
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_BACKEND_FRONTEND_NETWORK}
          gateway: ${DOCKER_BACKEND_FRONTEND_GATEWAY}
  remoteproxy:
    name: remoteproxy
    external: true
  postgres:
    name: postgres
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_BACKEND_POSTGRESQL_NETWORK}
          gateway: ${DOCKER_BACKEND_POSTGRESQL_GATEWAY}
